spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: StudentManagement
  datasource:
    url: jdbc:postgresql://localhost:5433/wildlife_conservation_db
    database: wildlife_conservation_db
    username: postgres
    password: 1111@2222@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

